apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  labels:
    app.kubernetes.io/name: kafka-manager
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/component: kafka-manager
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: kafka-m-client
      port: 80
      protocol: TCP
      targetPort: kafka-m-port
  selector:
    app.kubernetes.io/name: kafka-manager
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/component: kafka-manager
